#!/usr/bin/env python3
"""Generate db/seed/iso_reference.sql — the full ISO 3166-1 country and
ISO 4217 currency reference data promised by 000002_reference.up.sql.

Reads the Debian `iso-codes` package's JSON (apt install iso-codes), an
authoritative offline source, and emits idempotent INSERT ... ON CONFLICT DO
NOTHING statements. The generated SQL is committed so applying it needs only
psql (see `make seed-iso`); re-run this script when iso-codes updates.

Stdlib only, per the project dependency policy.

Usage: python3 db/seed/gen_iso_reference.py   (writes iso_reference.sql beside itself)
"""

import json
import pathlib
import re
import subprocess

ISO_CODES_DIR = pathlib.Path("/usr/share/iso-codes/json")
OUT = pathlib.Path(__file__).with_name("iso_reference.sql")

# ISO 4217 codes with no defined minor unit ("N/A" in the ISO published list):
# precious metals, bond-market index units, IMF/regional units of account, the
# testing code, and "no currency". currencies.minor_unit is NOT NULL, so these
# are excluded rather than given an invented value.
NO_MINOR_UNIT = {
    "XAU", "XAG", "XPD", "XPT",          # metals
    "XBA", "XBB", "XBC", "XBD",          # bond-market units
    "XDR", "XSU", "XUA",                 # supranational units of account
    "XTS", "XXX",                        # testing / no currency
}

# ISO 4217 minor units other than the default 2, per the ISO published list
# (hand-maintained: the iso-codes JSON does not carry minor units).
MINOR_UNITS = {
    **dict.fromkeys(
        ["BIF", "CLP", "DJF", "GNF", "ISK", "JPY", "KMF", "KRW", "PYG",
         "RWF", "UGX", "UYI", "VND", "VUV", "XAF", "XOF", "XPF"], 0),
    **dict.fromkeys(["BHD", "IQD", "JOD", "KWD", "LYD", "OMR", "TND"], 3),
    **dict.fromkeys(["CLF", "UYW"], 4),
}

# Display symbols (hand-maintained: symbols are not part of ISO 4217).
# Only well-established ones; everything else gets NULL. Not unique — the
# dollar family shares '$', and JPY/CNY share '¥'.
SYMBOLS = {
    **dict.fromkeys(["USD", "AUD", "CAD", "HKD", "MXN", "NZD", "SGD", "TWD"], "$"),
    **dict.fromkeys(["JPY", "CNY"], "¥"),
    **dict.fromkeys(["DKK", "ISK", "NOK", "SEK"], "kr"),
    "EUR": "€", "GBP": "£", "KRW": "₩", "INR": "₹", "RUB": "₽",
    "TRY": "₺", "THB": "฿", "VND": "₫", "ILS": "₪", "NGN": "₦",
    "PHP": "₱", "UAH": "₴", "PYG": "₲", "GHS": "₵", "CRC": "₡",
    "LAK": "₭", "MNT": "₮", "KZT": "₸", "AZN": "₼", "GEL": "₾",
    "KHR": "៛", "BDT": "৳", "BRL": "R$", "ZAR": "R",
    "PLN": "zł", "CZK": "Kč",
}


def q(s: str) -> str:
    """Quote a SQL string literal."""
    return "'" + s.replace("'", "''") + "'"


def iso_codes_version() -> str:
    try:
        out = subprocess.run(
            ["dpkg-query", "-W", "-f=${Version}", "iso-codes"],
            capture_output=True, text=True, check=True).stdout.strip()
        return out or "unknown"
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def load(name: str, key: str) -> list[dict]:
    with open(ISO_CODES_DIR / f"iso_{name}.json") as f:
        return json.load(f)[key]


def main() -> None:
    countries = sorted(load("3166-1", "3166-1"), key=lambda e: e["alpha_2"])
    currencies = sorted(load("4217", "4217"), key=lambda e: e["alpha_3"])
    currencies = [e for e in currencies if e["alpha_3"] not in NO_MINOR_UNIT]

    for e in countries:  # sanity-check the invariants the schema enforces
        assert re.fullmatch(r"[A-Z]{2}", e["alpha_2"]), e
        assert re.fullmatch(r"[A-Z]{3}", e["alpha_3"]), e
        assert re.fullmatch(r"[0-9]{3}", e["numeric"]), e
    for e in currencies:
        assert re.fullmatch(r"[A-Z]{3}", e["alpha_3"]), e
        assert re.fullmatch(r"[0-9]{3}", e["numeric"]), e

    lines = [
        "-- Full ISO 3166-1 country and ISO 4217 currency reference data.",
        f"-- Generated by gen_iso_reference.py from Debian iso-codes {iso_codes_version()};",
        "-- do not edit by hand — re-run the generator instead.",
        "--",
        "-- Idempotent and additive: ON CONFLICT DO NOTHING means existing rows",
        "-- (including the starter subset seeded by 000002_reference) are never",
        "-- modified. Apply with:  make seed-iso",
        "",
        "BEGIN;",
        "",
        f"-- ISO 3166-1: {len(countries)} countries.",
        "INSERT INTO countries (code, alpha3, numeric_code, name) VALUES",
    ]
    rows = [
        f"    ({q(e['alpha_2'])}, {q(e['alpha_3'])}, {q(e['numeric'])}, {q(e['name'])})"
        for e in countries
    ]
    lines.append(",\n".join(rows))
    lines += ["ON CONFLICT DO NOTHING;", ""]

    lines += [
        f"-- ISO 4217: {len(currencies)} currencies (codes with no defined minor",
        "-- unit — metals, bond indices, XDR and kin, XTS, XXX — are excluded).",
        "INSERT INTO currencies (code, numeric_code, name, symbol, minor_unit) VALUES",
    ]
    rows = []
    for e in currencies:
        code = e["alpha_3"]
        symbol = q(SYMBOLS[code]) if code in SYMBOLS else "NULL"
        rows.append(
            f"    ({q(code)}, {q(e['numeric'])}, {q(e['name'])}, "
            f"{symbol}, {MINOR_UNITS.get(code, 2)})"
        )
    lines.append(",\n".join(rows))
    lines += ["ON CONFLICT DO NOTHING;", "", "COMMIT;", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}: {len(countries)} countries, {len(currencies)} currencies")


if __name__ == "__main__":
    main()
