#!/usr/bin/env python3
"""Measure a repository's supply-chain footprint and size, for comparing
tadmor with its counterpart implementations (docs/counterpart-metrics.md).

    tools/measure.py [REPO] [--copied web/src/components/ui] [--manifest PATH] [--json]

Run from tadmor against any checkout, so every implementation is counted by
the same code. Standard library only.

The dependencies come from the repository's dependencies.json, the manifest
each implementation writes with its own tooling (tadmor's is
tools/dependencies.py): every third-party package with its category and
the publishing identities behind it. This tool knows no package manager;
it applies the shared definitions to the manifest. It reports, per category
(runtime / build / test):
  * dependency count       distinct third-party package versions
  * maintainers trusted    distinct publishing identities behind them
plus third-party source size as the manifest gives it, and, from git
itself, own source lines and history effort proxies.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

FORMAT = "tadmor-dependencies/1"
CATEGORIES = ("runtime", "build", "test")

SOURCE_EXTS = {
    ".go": "Go", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript",
    ".mjs": "JavaScript", ".cjs": "JavaScript", ".css": "CSS", ".html": "HTML",
    ".sql": "SQL", ".py": "Python", ".sh": "Shell", ".rs": "Rust", ".cs": "C#",
    ".java": "Java", ".kt": "Kotlin", ".ex": "Elixir", ".exs": "Elixir",
    ".rb": "Ruby", ".rake": "Ruby", ".ru": "Ruby", ".erb": "ERB", ".php": "PHP", ".cshtml": "Razor",
}
GENERATED_RE = re.compile(r"Code generated .* DO NOT EDIT|@generated|generated by", re.I)
# Shared across implementations (or comparison tooling), so never counted as
# anyone's own code.
SHARED_DIRS = ("spec/", "conformance/", "db/migrations/", "vendor/", "node_modules/", "tools/measure.py")


def git_files(repo):
    out = subprocess.run(["git", "-C", repo, "ls-files"], check=True, capture_output=True, text=True).stdout
    return [f for f in out.splitlines() if f]


def count_lines(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return sum(1 for line in fh if line.strip())
    except OSError:
        return 0


def load_manifest(path):
    """The manifest, checked against the format in docs/counterpart-metrics.md."""
    if not path.exists():
        sys.exit(f"measure.py: {path} not found. Each implementation commits a dependencies.json "
                 "(docs/counterpart-metrics.md, \"The dependency manifest\").")
    m = json.loads(path.read_text())
    if m.get("format") != FORMAT:
        sys.exit(f"measure.py: {path} has format {m.get('format')!r}, want {FORMAT!r}")
    for i, p in enumerate(m.get("packages", [])):
        missing = [k for k in ("ecosystem", "name", "version", "category", "identities", "evidence") if k not in p]
        if missing or p["category"] not in CATEGORIES:
            sys.exit(f"measure.py: {path} package {i} is malformed: missing {missing}, category {p.get('category')!r}")
    return m


def measure(repo, copied, manifest_path):
    files = git_files(repo)
    m = load_manifest(Path(manifest_path) if manifest_path else Path(repo, "dependencies.json"))
    cats = {c: {"deps": set(), "owners": set(), "unknown": 0} for c in CATEGORIES}
    for p in m["packages"]:
        cat = cats[p["category"]]
        cat["deps"].add(f"{p['ecosystem']}:{p['name']}@{p['version']}")
        if p["identities"] is None:
            cat["unknown"] += 1
        else:
            cat["owners"].update(p["identities"])
    # label -> {"bytes": n or None, "lines": n or None}
    third_party = {s["label"]: {"bytes": s.get("bytes"), "lines": s.get("lines")} for s in m.get("sources", [])}
    toolchains = set(m.get("toolchains", []))

    for path in copied:
        inside = [Path(repo, f) for f in files if f.startswith(path.rstrip("/") + "/")]
        third_party[f"copied into repo ({path})"] = {
            "bytes": sum(p.stat().st_size for p in inside), "lines": sum(count_lines(p) for p in inside)}

    own = {}
    for f in files:
        if f.startswith(SHARED_DIRS) or any(f.startswith(p.rstrip("/") + "/") for p in copied):
            continue
        lang = SOURCE_EXTS.get(Path(f).suffix)
        if not lang:
            continue
        p = Path(repo, f)
        try:
            head = "".join(p.open(encoding="utf-8", errors="replace").readlines()[:5])
        except OSError:
            continue
        if GENERATED_RE.search(head):
            continue
        own[lang] = own.get(lang, 0) + count_lines(p)

    log = subprocess.run(["git", "-C", repo, "log", "--format=%cs"], check=True, capture_output=True, text=True).stdout.split()
    effort = {"commits": len(log), "days_with_commits": len(set(log)),
              "first_commit": min(log) if log else None, "last_commit": max(log) if log else None}

    def summary(names):
        deps, owners = set(), set()
        unknown = 0
        for n in names:
            deps |= cats[n]["deps"]
            owners |= cats[n]["owners"]
            unknown += cats[n]["unknown"]
        return {"dependencies": len(deps), "maintainers": len(owners), "maintainers_unknown_for": unknown,
                "maintainer_list": sorted(owners)}

    return {
        "repo": os.path.abspath(repo),
        "manifest_generator": m.get("generator"),
        "commit": subprocess.run(["git", "-C", repo, "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip(),
        "categories": {c: summary([c]) for c in cats},
        "shipped_and_build": summary(["runtime", "build"]),
        "everything": summary(["runtime", "build", "test"]),
        "toolchains": sorted(toolchains),
        "third_party": third_party,
        "own_lines": dict(sorted(own.items())),
        "own_lines_total": sum(own.values()),
        "effort": effort,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("repo", nargs="?", default=".")
    ap.add_argument("--copied", action="append", default=[],
                    help="third-party source copied into the repo, counted as third-party lines")
    ap.add_argument("--manifest", help="read the manifest here instead of REPO/dependencies.json")
    ap.add_argument("--json", action="store_true", help="print the full report as JSON")
    args = ap.parse_args()
    r = measure(args.repo, args.copied, args.manifest)
    if args.json:
        json.dump(r, sys.stdout, indent=2)
        print()
        return
    print(f"{r['repo']} @ {r['commit']} (manifest by {r['manifest_generator']})\n")
    print(f"{'category':<20}{'dependencies':>14}{'maintainers':>14}")
    rows = [(c, r["categories"][c]) for c in ("runtime", "build", "test")]
    rows += [("runtime+build", r["shipped_and_build"]), ("everything", r["everything"])]
    for name, s in rows:
        note = f"  ({s['maintainers_unknown_for']} pkgs without identities)" if s["maintainers_unknown_for"] else ""
        print(f"{name:<20}{s['dependencies']:>14}{s['maintainers']:>14}{note}")
    print(f"\ntoolchains: {', '.join(r['toolchains'])}")
    print(f"\n{'third-party source':<44}{'bytes':>12}{'lines':>12}")
    for k, v in r["third_party"].items():
        b = "?" if v["bytes"] is None else v["bytes"]
        n = "n/a" if v["lines"] is None else v["lines"]
        print(f"  {k:<42}{b:>12}{n:>12}")
    print("\nown source lines (non-blank, excluding generated, spec/ and conformance/):")
    for k, v in r["own_lines"].items():
        print(f"  {k:<40}{v:>12}")
    print(f"  {'total':<40}{r['own_lines_total']:>12}")
    e = r["effort"]
    print(f"\ngit: {e['commits']} commits on {e['days_with_commits']} days, {e['first_commit']} .. {e['last_commit']}")


if __name__ == "__main__":
    main()
