#!/usr/bin/env python3
"""Measure a repository's supply-chain footprint and size, for comparing
tadmor with its counterpart implementations (docs/counterpart-metrics.md).

    tools/measure.py [REPO] [--test-dir e2e] [--copied web/src/components/ui]
                     [--offline] [--json]

Run from tadmor against any checkout, so every implementation is measured by
the same code. Standard library only.

Reports, per category (runtime / build / test):
  * dependency count       distinct third-party package versions resolved
  * maintainers trusted    distinct publishing identities behind them
plus third-party source size (bytes; lines where the source is on disk), own
source lines, and git-history effort proxies.

Ecosystems understood so far: Go modules (vendor/modules.txt) and pnpm
(pnpm-lock.yaml v9). Add a parser here when a counterpart needs another
(Cargo.lock, packages.lock.json, ...). Maintainer lookups for npm read public
registry metadata (no package code is fetched); --offline skips them.
"""

import argparse
import concurrent.futures
import json
import os
import re
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

# Where the measuring machine builds; optional npm packages for other
# platforms (fsevents, other esbuild binaries) are never installed there.
PLATFORM_OS, PLATFORM_CPU = "linux", "x64"

CACHE = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "tadmor-metrics" / "npm-metadata.json"

SOURCE_EXTS = {
    ".go": "Go", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript",
    ".mjs": "JavaScript", ".cjs": "JavaScript", ".css": "CSS", ".html": "HTML",
    ".sql": "SQL", ".py": "Python", ".sh": "Shell", ".rs": "Rust", ".cs": "C#",
    ".java": "Java", ".kt": "Kotlin", ".ex": "Elixir", ".exs": "Elixir",
    ".rb": "Ruby", ".php": "PHP",
}
GENERATED_RE = re.compile(r"Code generated .* DO NOT EDIT|@generated|generated by", re.I)
# Shared across implementations (or comparison tooling), so never counted as
# anyone's own code.
SHARED_DIRS = ("spec/", "conformance/", "db/migrations/", "vendor/", "node_modules/", "tools/measure.py")


def git_files(repo):
    out = subprocess.run(["git", "-C", repo, "ls-files"], check=True, capture_output=True, text=True).stdout
    return [f for f in out.splitlines() if f]


def count_lines(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return sum(1 for line in fh if line.strip())
    except OSError:
        return 0


# ---------------------------------------------------------------------------
# Go modules
# ---------------------------------------------------------------------------

def go_modules(repo):
    """Modules compiled into the build, from vendor/modules.txt (those with at
    least one package listed)."""
    path = Path(repo, "vendor", "modules.txt")
    if not path.exists():
        return []
    mods, current, used = [], None, False
    for line in path.read_text().splitlines():
        if line.startswith("# ") and not line.startswith("## "):
            if current and used:
                mods.append(current)
            parts = line[2:].split()
            current, used = (parts[0], parts[1] if len(parts) > 1 else ""), False
        elif line and not line.startswith("#"):
            used = True
    if current and used:
        mods.append(current)
    return mods


def go_owner(module):
    """The publishing identity behind a Go module: its repository owner."""
    if module.startswith("golang.org/x/"):
        return "go-project (golang.org/x)"
    parts = module.split("/")
    if parts[0] in ("github.com", "gitlab.com", "bitbucket.org", "codeberg.org") and len(parts) > 1:
        return f"{parts[0]}/{parts[1]}"
    return parts[0]


# ---------------------------------------------------------------------------
# pnpm lockfile (v9)
# ---------------------------------------------------------------------------

def unquote(s):
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "'\"":
        return s[1:-1]
    return s


def parse_pnpm_lock(path):
    """Return (importer deps by kind, package metadata, snapshot deps)."""
    importers = {"dependencies": set(), "devDependencies": set(), "optionalDependencies": set()}
    packages, snapshots = {}, {}
    section = None
    imp_kind = imp_name = None
    key = sub = None
    for raw in Path(path).read_text().splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        text = raw.strip()
        if indent == 0:
            section = text.rstrip(":")
            continue
        if section == "importers":
            if indent == 4:
                imp_kind = text.rstrip(":") if text.rstrip(":") in importers else None
            elif indent == 6 and imp_kind:
                imp_name = unquote(text.rstrip(":"))
            elif indent == 8 and imp_kind and text.startswith("version:"):
                importers[imp_kind].add(f"{imp_name}@{unquote(text.split(':', 1)[1])}")
        elif section == "packages":
            if indent == 2:
                key = unquote(text.rstrip(":"))
                packages[key] = {}
            elif indent == 4 and key is not None and ":" in text:
                k, v = text.split(":", 1)
                if k in ("os", "cpu"):
                    packages[key][k] = [unquote(x) for x in v.strip().strip("[]").split(",") if x.strip()]
        elif section == "snapshots":
            if indent == 2:
                key = unquote(text.rstrip(":"))
                snapshots[key] = []
                sub = None
            elif indent == 4:
                sub = text.rstrip(":") if text.rstrip(":") in ("dependencies", "optionalDependencies") else None
            elif indent == 6 and sub and ":" in text:
                name, ver = _split_quoted(text) if text[0] in "'\"" else text.split(":", 1)
                snapshots[key].append((unquote(name), unquote(ver), sub == "optionalDependencies"))
    return importers, packages, snapshots


def _split_quoted(text):
    q = text[0]
    end = text.index(q, 1)
    return text[: end + 1], text[end + 2 :]


def base_key(snapshot_key):
    """'echarts-for-react@3.0.6(echarts@5.6.0)' -> 'echarts-for-react@3.0.6'."""
    return snapshot_key.split("(", 1)[0]


def split_name_version(key):
    at = key.rindex("@")
    return key[:at], key[at + 1 :]


def platform_ok(meta):
    oss, cpus = meta.get("os"), meta.get("cpu")
    ok_os = not oss or any(o == PLATFORM_OS or (o.startswith("!") and o[1:] != PLATFORM_OS) for o in oss)
    ok_cpu = not cpus or any(c == PLATFORM_CPU or (c.startswith("!") and c[1:] != PLATFORM_CPU) for c in cpus)
    return ok_os and ok_cpu


def closure(roots, packages, snapshots):
    """Package versions reachable from roots, as installed on this platform."""
    seen, stack = set(), list(roots)
    while stack:
        key = stack.pop()
        base = base_key(key)
        if key in seen or not platform_ok(packages.get(base, {})):
            continue
        seen.add(key)
        for name, ver, _optional in snapshots.get(key, []):
            stack.append(f"{name}@{ver}")
    return {base_key(k) for k in seen}


def npm_metadata(keys, offline):
    """Map package@version -> {"maintainers": npm usernames with publish
    rights at that version, "bytes": unpacked size}, from registry metadata.
    Cached across runs; None where unknown (--offline and not cached)."""
    cache = {}
    if CACHE.exists():
        cache = json.loads(CACHE.read_text())
    missing = [k for k in keys if k not in cache]
    if missing and not offline:
        def fetch(key):
            name, ver = split_name_version(key)
            url = f"https://registry.npmjs.org/{urllib.parse.quote(name, safe='@')}/{ver}"
            with urllib.request.urlopen(url, timeout=30) as resp:
                doc = json.load(resp)
            return key, {
                "maintainers": sorted({m["name"] for m in doc.get("maintainers", []) if m.get("name")}),
                "bytes": doc.get("dist", {}).get("unpackedSize"),
            }
        with concurrent.futures.ThreadPoolExecutor(8) as pool:
            for key, names in pool.map(fetch, missing):
                cache[key] = names
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        CACHE.write_text(json.dumps(cache, indent=0, sort_keys=True))
    return {k: cache.get(k) for k in keys}


def npm_package_lines(lock_dir, keys):
    """Non-blank JS lines installed for these packages, if node_modules exists."""
    store = Path(lock_dir, "node_modules", ".pnpm")
    if not store.exists():
        return None
    total = 0
    for key in keys:
        name, ver = split_name_version(key)
        pkg = store / f"{name.replace('/', '+')}@{ver}" / "node_modules" / name
        for root, _dirs, files in os.walk(pkg):
            for f in files:
                if f.endswith((".js", ".mjs", ".cjs")):
                    total += count_lines(os.path.join(root, f))
    return total


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def measure(repo, test_dirs, copied, offline):
    files = git_files(repo)
    cats = {c: {"deps": set(), "owners": set(), "unknown": 0} for c in ("runtime", "build", "test")}
    third_party = {}  # label -> {"bytes": n or None, "lines": n or None}

    mods = go_modules(repo)
    for mod, ver in mods:
        cats["runtime"]["deps"].add(f"go:{mod}@{ver}")
        cats["runtime"]["owners"].add(go_owner(mod))
    if mods:
        vendored = [Path(repo, f) for f in files if f.startswith("vendor/")]
        third_party["Go vendor/ (runtime)"] = {
            "bytes": sum(p.stat().st_size for p in vendored),
            "lines": sum(count_lines(p) for p in vendored if p.suffix == ".go"),
        }

    toolchains = set()
    if Path(repo, "go.mod").exists():
        toolchains.add("Go project (toolchain)")
    for lock in [f for f in files if f.endswith("pnpm-lock.yaml") and "node_modules/" not in f]:
        lock_dir = str(Path(repo, lock).parent)
        rel_dir = str(Path(lock).parent)
        importers, packages, snapshots = parse_pnpm_lock(Path(repo, lock))
        prod = closure(importers["dependencies"] | importers["optionalDependencies"], packages, snapshots)
        dev = closure(importers["devDependencies"], packages, snapshots) - prod
        is_test = any(rel_dir == d or rel_dir.startswith(d + "/") for d in test_dirs)
        groups = [("test", prod | dev)] if is_test else [("runtime", prod), ("build", dev)]
        toolchains.update({"Node.js project (runtime for tooling)", "pnpm (via corepack)"})
        meta = npm_metadata(sorted(prod | dev), offline)
        for cat, keys in groups:
            size = 0
            for k in keys:
                cats[cat]["deps"].add(f"npm:{k}")
                if meta.get(k) is None:
                    cats[cat]["unknown"] += 1
                    size = None
                else:
                    cats[cat]["owners"].update(f"npm:{n}" for n in meta[k]["maintainers"])
                    if size is not None and meta[k]["bytes"] is not None:
                        size += meta[k]["bytes"]
            third_party[f"npm {rel_dir} ({cat})"] = {"bytes": size, "lines": npm_package_lines(lock_dir, keys)}

    for path in copied:
        inside = [Path(repo, f) for f in files if f.startswith(path.rstrip("/") + "/")]
        third_party[f"copied into repo ({path})"] = {
            "bytes": sum(p.stat().st_size for p in inside), "lines": sum(count_lines(p) for p in inside)}

    own = {}
    for f in files:
        if f.startswith(SHARED_DIRS) or any(f.startswith(p.rstrip("/") + "/") for p in copied):
            continue
        lang = SOURCE_EXTS.get(Path(f).suffix)
        if not lang:
            continue
        p = Path(repo, f)
        try:
            head = "".join(p.open(encoding="utf-8", errors="replace").readlines()[:5])
        except OSError:
            continue
        if GENERATED_RE.search(head):
            continue
        own[lang] = own.get(lang, 0) + count_lines(p)

    log = subprocess.run(["git", "-C", repo, "log", "--format=%cs"], check=True, capture_output=True, text=True).stdout.split()
    effort = {"commits": len(log), "days_with_commits": len(set(log)),
              "first_commit": min(log) if log else None, "last_commit": max(log) if log else None}

    def summary(names):
        deps, owners = set(), set()
        unknown = 0
        for n in names:
            deps |= cats[n]["deps"]
            owners |= cats[n]["owners"]
            unknown += cats[n]["unknown"]
        return {"dependencies": len(deps), "maintainers": len(owners), "maintainers_unknown_for": unknown,
                "maintainer_list": sorted(owners)}

    return {
        "repo": os.path.abspath(repo),
        "commit": subprocess.run(["git", "-C", repo, "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip(),
        "categories": {c: summary([c]) for c in cats},
        "shipped_and_build": summary(["runtime", "build"]),
        "everything": summary(["runtime", "build", "test"]),
        "toolchains": sorted(toolchains),
        "third_party": third_party,
        "own_lines": dict(sorted(own.items())),
        "own_lines_total": sum(own.values()),
        "effort": effort,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("repo", nargs="?", default=".")
    ap.add_argument("--test-dir", action="append", default=None,
                    help="directory whose lockfile is test-only tooling (default: e2e)")
    ap.add_argument("--copied", action="append", default=[],
                    help="third-party source copied into the repo, counted as third-party lines")
    ap.add_argument("--offline", action="store_true", help="skip npm registry maintainer lookups")
    ap.add_argument("--json", action="store_true", help="print the full report as JSON")
    args = ap.parse_args()
    r = measure(args.repo, args.test_dir or ["e2e"], args.copied, args.offline)
    if args.json:
        json.dump(r, sys.stdout, indent=2)
        print()
        return
    print(f"{r['repo']} @ {r['commit']}\n")
    print(f"{'category':<20}{'dependencies':>14}{'maintainers':>14}")
    rows = [(c, r["categories"][c]) for c in ("runtime", "build", "test")]
    rows += [("runtime+build", r["shipped_and_build"]), ("everything", r["everything"])]
    for name, s in rows:
        note = f"  ({s['maintainers_unknown_for']} pkgs not looked up)" if s["maintainers_unknown_for"] else ""
        print(f"{name:<20}{s['dependencies']:>14}{s['maintainers']:>14}{note}")
    print(f"\ntoolchains: {', '.join(r['toolchains'])}")
    print(f"\n{'third-party source':<44}{'bytes':>12}{'lines':>12}")
    for k, v in r["third_party"].items():
        b = "?" if v["bytes"] is None else v["bytes"]
        n = "n/a" if v["lines"] is None else v["lines"]
        print(f"  {k:<42}{b:>12}{n:>12}")
    print("\nown source lines (non-blank, excluding generated, spec/ and conformance/):")
    for k, v in r["own_lines"].items():
        print(f"  {k:<40}{v:>12}")
    print(f"  {'total':<40}{r['own_lines_total']:>12}")
    e = r["effort"]
    print(f"\ngit: {e['commits']} commits on {e['days_with_commits']} days, {e['first_commit']} .. {e['last_commit']}")


if __name__ == "__main__":
    main()
